apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmp-vm
  name: vmp-vm
spec:
  type: NodePort
  ports:
    - port: 9444
      protocol: TCP
      targetPort: 9444
  selector:
    app: vmp-vm
